apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: simple # The name of the app
  namespace: default
  annotations:
    subdomain: simple6
spec:
  template:
    spec:
      containers:
        - image: registry.tlnk.fr/library/simple-app
